---
title: "Experiment 8"
format: html
editor: visual
---

## Z-Test for two sample means

#### Problem: size1 = 500, mean1 = 20, size2 = 400, mean2 = 15. population s.d. = 4. test at 5% significance level whether both sampes are from the same populatoin.  Hypotheses:

```{r}
xbar = 20
ybar = 15

sigma = 4

n1 = 500
n2 = 400

z = (xbar - ybar)/(sigma *sqrt((1/n1) + (1/n2)))
z
```

```{r}
alpha = 0.05

#critical value
zalpha = qnorm(1 - alpha/2)
zalpha

#decision
if(abs(z) <= zalpha) {
  print("Accept H0")
} else{
  print("Reject H0")
}


```

#### Problem 2: test at 5%

```{r}
n1 = 1000
n2 = 2000
mean1 = 67.5
mean2 = 68

sd = 2.5

z = (mean1-mean2)/(sd*sqrt((1/n1) + (1/n2)))
z

```

```{r}
alpha = 0.05

zalpha = qnorm(1-alpha/2)
zalpha

if(abs(z) <= zalpha){
  print("H0 accepted")
} else{
  print("H0 rejected")
}
```

```{r}
p1 = 0.20
p2 = 0.185

n1 = 900
n2 = 1600

# Pooled proportion (Population)
P = (n1*p1 + n2*p2) / (n1 + n2)
Q = 1 - P

# Test statistic
z = (p1-p2)/(sqrt(P*Q*((1/n1) + (1/n2))))
z
```

```{r}
alpha = 0.05
zalpha = qnorm(1 - alpha/2)
zalpha

# Decision
if(abs(z) <= zalpha){
  print("H0 accepted")
} else{
  print("H0 rejected")
}
```

Conclusion: There's no significant difference between the two proportions

```{r}
p1 = 0.20 # vizag
p2 = 0.15 # andhra

# we're givem. p1 > p2

n1 = 900
n2 = 1200

P = (n1*p1+ n2*p2)/(n1+n2)
Q = 1-P

z = (p1-p2)/sqrt(P*Q*((1/n1) + (1/n2)))
z

alpha = 0.01
zalpha = qnorm(1-alpha/2) # two tailed test
zalpha1 =  qnorm(1-alpha) # right tailed test when P1 > P2. We'll use it this time
zalpha2 = qnorm(alpha) # left tailed test



zalpha
zalpha1
zalpha2

# using right tailed test
if(abs(z) <= zalpha1){
  print("H0 accepted")
} else{
  print("H0 rejected")
}


```

```{r}

zsum.test(mean.x, sigma.x, n.x, mean.y, sigma.y, n.y, alternative = "two.sided", mu, conf.level = 0.95)

```

```{r}
prop.test(x, n, p = p0, alternative = "two.sided", correct  = FALSE) # false so that ztest otherwise, true= chi-test
```

```{r}
prop.test(c(x1, x2), c(n1, n2), alternative = "two.sided", correct = FALSE)
```
